// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/capslook-home/CapslookHome.tsx": () => import("../components/mockups/capslook-home/CapslookHome.tsx"),
  "./components/mockups/capslook-sections/AICapsule.tsx": () => import("../components/mockups/capslook-sections/AICapsule.tsx"),
  "./components/mockups/capslook-sections/Clients.tsx": () => import("../components/mockups/capslook-sections/Clients.tsx"),
  "./components/mockups/capslook-sections/DayPlan.tsx": () => import("../components/mockups/capslook-sections/DayPlan.tsx"),
  "./components/mockups/capslook-sections/Finance.tsx": () => import("../components/mockups/capslook-sections/Finance.tsx"),
  "./components/mockups/capslook-sections/Profile.tsx": () => import("../components/mockups/capslook-sections/Profile.tsx")
};
